#!/usr/bin/awk -f
BEGIN{
	for(i=1;i<ARGC;i++){
		xdg_select_file(ARGV[i])
	}
}

function xdg_select_file(infile,	cmd_get,cmd_run){
	cmd_get="LC_MESSAGES=C gio info --attributes= " infile
	while((cmd_get|getline)>0){
		if($1~/^uri:/){
		cmd_run="dbus-send --session --print-reply --dest=org.freedesktop.FileManager1 --type=method_call /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:\""$2"\" string:\"\""
		break
		}
	}
	system(cmd_run)
	close(cmd_run)
}
